---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csye7125-consumer.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
   type: {{ .Values.type }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    type: {{ .Values.type }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "csye7125-consumer.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    type: {{ .Values.type }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  serviceName: {{ include "csye7125-consumer.fullname" . }}-headless
  replicas: {{ .Values.replicaCountss }}
  selector:
    matchLabels:
      type: {{ .Values.type }}
  template:
    metadata:
      labels:
        type: {{ .Values.type }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag | default .Chart.AppVersion }}"
          env:
            {{- range .Values.postgres.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                pg_isready -U $POSTGRES_USER -d POSTGRES_DB -h 127.0.0.1
            initialDelaySeconds: {{ .Values.livenessProbeP.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbeP.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbeP.failureThreshold }}
            successThreshold: {{ .Values.livenessProbeP.successThreshold }}
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                pg_isready -U $POSTGRES_USER -d POSTGRES_DB -h 127.0.0.1
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /var/lib/mydb
      volumes:
        - name: data
          emptyDir: {}