# Default values for csye7125.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
replicaCountss: 1

namespace: ns3
type: database

name: csye7125-consumer

app:
  image: chlokesh1306/cve-consumer
  pullPolicy: Always
  tag: 1.2.3
  env:
    - name: DB_HOST
      value: csye7125-consumer-headless.ns3.svc.cluster.local
    - name: DB_USER
      value: postgres
    - name: DB_PASSWORD
      value: admin
    - name: DB_NAME
      value: cve
    - name: DB_PORT
      value: 5432
    - name: KAFKA_BROKERS
      value: "kafka-broker-headless.ns2.svc.cluster.local:9092"
    - name: KAFKA_TOPIC
      value: "cve"

postgres:
  image: postgres
  pullPolicy: IfNotPresent
  tag: latest
  env:
    - name: POSTGRES_DB
      value: cve
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_USER
      value: postgres

initContainer:
  image: chlokesh1306/database-migration
  pullPolicy: IfNotPresent
  tag: 1.0.3
  env:
    - name: FLYWAY_URL
      value: jdbc:postgresql://csye7125-consumer-headless.ns3.svc.cluster.local:5432/cve
    - name: FLYWAY_USER
      value: postgres
    - name: FLYWAY_PASSWORD
      value: admin
    - name: FLYWAY_SCHEMAS
      value: cve

imagePullSecrets:
  name: dockerhub
  dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjaGxva2VzaDEzMDYiLCJwYXNzd29yZCI6ImRja3JfcGF0X3pxY3BVajZKcDloUWpBNmJtSDZpUUJmNDBNTSIsImVtYWlsIjoiY2hhbGxhZ3VsbGEubEBub3J0aGVhc3Rlcm4uZWR1IiwiYXV0aCI6IlkyaHNiMnRsYzJneE16QTJPbVJqYTNKZmNHRjBYM3B4WTNCVmFqWktjRGxvVVdwQk5tSnRTRFpwVVVKbU5EQk5UUT09In19fQ==
nameOverride: ""
fullnameOverride: ""

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 15
  failureThreshold: 5
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
